### ISSUE TITLE
"By using" at the beginning of a sentence incorrectly flagged

### ISSUE THREAD

**Issue by emteelb** [redhat-documentation/vale-at-red-hat#514]
A sentence that begins with "By using" incorrectly trips this `TermsSuggestions.yml` rule:

```
"(?<!by) using": by using|that uses
```

This would fix it:

```
"(?<![Bb]y) using": by using|that uses
```

I don't think I noticed mention of this in #208 but if work is being done there, perhaps this fix could be added to that work?

Otherwise, happy to submit something separately.

**Comment by rohennes** [comment]
Thank you @emteelb. This is a good catch and is not really related to #208.

Please feel free to open a PR to fix this issue. Or somebody in our community can pick it up. 

I have verified your approach [here](https://studio.vale.sh/s/76a3a336c073b0a3cd79df1e4e7d6d17). I think you don't need to add "By using" to the test fixture (`.vale/fixtures/RedHat/TermsSuggestions/testinvalid.adoc` ) for this rule because the bug found in #208 might cause an issue there. So just a change the style (`.vale/styles/RedHat/TermsSuggestions.yml`) as outlined above is enough in this case.

FYI - We are participating in [Hacktoberfest](https://hacktoberfest.com/), so it would be good to open the PR after Oct 1st and we will try to get it closed before Oct 31st to ensure it's a qualifying PR for the event. :smiley_cat:

**Comment by emteelb** [comment]
@rohennes Happy to make a PR and open after 1 Oct. I was not aware of studio.vale.sh. This will be a big improvement to my Vale style rule writing workflow over regex101. Appreciate the mention and thanks for your guidance.

**Comment by rohennes** [comment]
Great, thanks so much!!
