### ISSUE TITLE
Vale linter discourages the use of "Previously" 

### ISSUE THREAD

**Issue by dfitzmau** [redhat-documentation/vale-at-red-hat#519]
**Describe the bug**
The OCP release note team regularly uses the term "Previously" to initiate a bug text release note. The Vale linter outputs a message that discourages the use of this word in favour of "Before this update". The use of "Previously" is clearer in my opinion, as it does not contain the vague referent "this". 

Examples:
See the attached screenshot of the output from running the Vale extension in Codium.

**Suggestion**
Update the Vale linter index for release notes to include "Previously" as a recommended term. Remove the flag set on this word. 

![Screenshot from 2023-05-02 08-59-08](https://user-images.githubusercontent.com/57954076/235901846-5456e5a0-f577-4c74-aedc-0182fd8649d5.png)

**Comment by dfitzmau** [comment]
Addressed in #522

**Comment by rolfedh** [comment]
Those suggestions are based on https://redhat-documentation.github.io/supplementary-style-guide/#release-notes.

I believe Steve Goodman, @BrianB, and others on the style council developed these release note guidelines. I'd recommend consulting with them.

If I recall, although "previously" and "now" sound natural, they were to be avoided because they are _relative_ references whose meaning is ambiguous when there are multiple time frames (releases) in question: Previous to what? Now, when? In other words, someone reading the release notes sees various "nows" referring to entirely different releases and "previouses" that overlap with "nows."

At one point, the release notes maintainer for openshift-docs was enforcing these style rules, but they may have fallen into disuse. Before removing these rules, I recommend conversing with the style council and the openshift-docs core team. I'll +1 any decision that comes from those conversations.

**Comment by aireilly** [comment]
@dfitzmau can we close this?

**Comment by dfitzmau** [comment]
> @dfitzmau can we close this?

Yes, this PR will now be closed based on https://github.com/openshift/openshift-docs/pull/59603/files
