### ISSUE TITLE
Add an exception for "deserialized" so that RedHat.Spelling does not generate a warning.

### ISSUE THREAD

**Issue by rolfedh** [redhat-documentation/vale-at-red-hat#581]
**Is your feature request related to a problem? Describe.**

Add an exception for "deserialized" so that RedHat.Spelling does not generate a warning.

Possible variants to include:
- deserialization
- deserialize

The following sources demonstrate that the spelling of this word and its variants are valid:
- https://hazelcast.com/glossary/deserialization/
- https://www.google.com/search?q=deserialized

**Additional context**

```
[rdlugyhe@rdlugyhe-thinkpadt14sgen2i rhbq-quarkus]$ vale modules/ref_changes-that-affect-backwards-compatibility.adoc --minAlertLevel=warning

 modules/ref_changes-that-affect-backwards-compatibility.adoc
 35:70  warning  Use correct American English    RedHat.Spelling 
                 spelling. Did you really mean                   
                 'deserialized'?                                 
 36:96  warning  Use correct American English    RedHat.Spelling 
                 spelling. Did you really mean                   
                 'deserialized'?           
```

FYI @michelle-purcell

**Comment by rohennes** [comment]
Can we get this one in Hacktoberfest @rolfedh ? A related PR should be opened after Oct 1st and closed before Oct 31st. Will you take it or we can unassign it otherwise?

The effort here is to add deserialize to the [Spelling](https://github.com/redhat-documentation/vale-at-red-hat/blob/main/.vale/styles/RedHat/Spelling.yml) rule. And also to the related test [fixture](https://github.com/redhat-documentation/vale-at-red-hat/blob/main/.vale/fixtures/RedHat/Spelling/testvalid.adoc).

**Comment by rolfedh** [comment]
Good first issue, @rohennes. Thanks!
